name: Build EXE on Release

on:
  release:
    types: [created]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/addition.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Addition'
          options: --onefile, --name "Addition App", --windowed
